language: python
python: 2.7
sudo: false
os:
  - linux
  - osx
env:
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
